export enum IPC_CMD {
    DEBUG_MSG = "DEBUG_MSG",
    STORE_GET_EXCHANGE_ACCOUNT_INFOS = "STORE_GET_EXCHANGE_ACCOUNT_INFOS",    
    NOTIFY_EXCHANGE_ACCOUNT_INFOS = "NOTIFY_EXCHANGE_ACCOUNT_INFOS",
    STORE_ADD_EXCHANGE_ACCOUNT_INFOS = "STORE_ADD_EXCHANGE_ACCOUNT_INFOS",
    STORE_UPDATE_EXCHANGE_ACCOUNT_INFOS = "STORE_UPDATE_EXCHANGE_ACCOUNT_INFOS",
    STORE_DELETE_EXCHANGE_ACCOUNT_INFOS = "STORE_DELETE_EXCHANGE_ACCOUNT_INFOS",
    STORE_DELETE_ALL_EXCHANGE_ACCOUNT_INFOS = "STORE_DELETE_ALL_EXCHANGE_ACCOUNT_INFOS",

    GET_ALL_JOB_WORKERS = "GET_ALL_JOB_WORKERS",
    NOTIFY_JOB_WORKERINFOS = "NOTIFY_JOB_WORKERINFOS",
    ADD_JOB_WORKER = "ADD_JOB_WORKER",
    DELETE_JOB_WORKER = "DELETE_JOB_WORKER",
    UPDATE_JOB_WORKER_EXIT_TARGET_PRIMIUM = "UPDATE_JOB_WORKER_EXIT_TARGET_PRIMIUM",
    START_JOB_WORKERS = "START_JOB_WORKERS",
    STOP_JOB_WORKERS = "STOP_JOB_WORKERS",

    SET_EXCHANGE_RATE_MONITOR_ON_OFF = "SET_EXCHANGE_RATE_MONITOR_ON_OFF",
    GET_ENV_INFO = "GET_ENV_INFO",
    SET_USER_INFO = "SET_USER_INFO",
    GET_STORE_DATE = "GET_STORE_DATE",
    SET_STORE_DATE = "SET_STORE_DATE",
    REQUEST_MARKET_INFO = "REQUEST_MARKET_INFO",
    NOTIFY_MARKET_INFO = "NOTIFY_MARKET_INFO",

    GET_ALL_TRADE_JOB_INFOS = "GET_ALL_TRADE_JOB_INFOS",
    NOTIFY_TRADE_JOB_INFOS = "NOTIFY_TRADE_JOB_INFOS",

    REQUEST_PRIMIUM_CHART_DATA = "REQUEST_PRIMIUM_CHART_DATA",
    NOTIFY_PRIMIUM_CHART_DATA = "NOTIFY_PRIMIUM_CHART_DATA",
}